
# <center style = 'padding : 20px; border : 3px green double; margin-bottom : -30px;' >Project Euler : Problems 1 to 20.</center>
<p style="text-align : right">Louis SALOMÉ</right>

All the following problems come from https://projecteuler.net/.

I hope you'll find some nice ideas in this code even if the algorithms are sometimes far from optimal performances.

Here is my friend's key =========> 804341_ax5HbE1YT04eusYj9FMdp1tcJpoREusm

In [1]:
# IMPORT MODULES
import numpy as np
import math

In [2]:
# Here is my personal library in the same repository
import MyLibrary
from MyLibrary import *

#### Problem 1 
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [3]:
S = 0
for i in range(1000):
    if (i%3 == 0) or (i%5 == 0) :
        S+=i

print(S)

233168

#### Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [4]:
S = 0 # I often use leter S for the sums
F0 = 0
F1 = 1

while F1 <= 4000000 :
    x = F1
    F1 = F0 + F1 #Fibonacci recurrence
    F0 = x
    if F1 % 2 == 0 :
        S += F1

print(S)

4613732

#### Problem 3 
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [5]:
n = 600851475143
divisor=2
maxdivisor= 0

while divisor < n:
    while (n % divisor != 0):
        divisor+=1
    n/=divisor
    maxdivisor=divisor

print(maxdivisor)

6857

#### Problem 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [6]:
# I just tried with the biggest possible numbers
# This is not a nice way to do it..
i = 1000
while i>900:
    i+=-1
    for j in range(999-i) :
        test = i*(999-j)
        if est_palindrome(int_to_list(test)):
            print(test)

888888
861168
886688
906609
824428
819918

#### Problem 5 
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [7]:
# You just have to decompose the number we search in prime numbers
# It must be 1*2*3*4*...*19*20 but with the least prime you need
#          1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
solution = 1*2*3*2*5*1*7*2*3*1* 11*1* 13*1* 1* 2* 17*1* 19* 1
print(solution)

232792560

#### Problem 6 
The sum of the squares of the first ten natural numbers is,

1^2 + 2^2 + ... + 10^2 = 385
The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)^2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum

In [8]:
# Know your math
# sum of k from 1 to n is n(n+1)/2
# sum of k^2 from 1 to n is n(n+1)(2n+1/6
S1 = 1000*1001*2001/6
S2 = (1000*1001/2)**2
print(int(S2-S1))

250166416500

#### Problem 7 

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [9]:
# Here is use the Sieve of Eratosthenes (crible d'Eratosthenes in French)
# More infos : https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes
L = crible(120000)
print(L[10000])

104743

#### Problem 8 
The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [10]:
# I copied the grid in a text file, locted in src directory
text_file = open("src/8.txt", "r")
lines = text_file.readlines()
text_file.close()

grid = np.array([[int(lines[j][i]) for i in range(len(lines[0][:-1]))] for j in range(len(lines))])
h,w = grid.shape

maxi=0
for i in range(h) :
    for j in range(w):
        n = grid[i][j:j+13].prod()
        if n > maxi :
            maxi = n

print(maxi)

2091059712

#### Problem 9 
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a^2 + b^2 = c^2
For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [11]:
# Let's try every possibilities
# There are not so much
foundIt=False
a=0
while (a<1000 and not(foundIt)) :
    a+=1
    b=a
    while (b<999-a and not(foundIt)):
        b+=1
        if (a**2 + b**2 == (1000-a-b)**2):
            foundIt = True

print(a*b*(1000-a-b))

31875000

#### Problem 10
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [12]:
S = 0
for i in range(2,2*10**6+1):
    if is_prime(i):
        S += i
print(S)

142913828922

#### Problem 11
In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [13]:
text_file = open("src/11.txt", "r")
lines = text_file.readlines()
lines[-1] += '\n' #uniformizing ...
text_file.close()

M = []
for i in range(len(lines)):
    str = lines[i][:-1]
    M.append([])
    for j in range(int(len(str)/3)+1):
        M[i].append(int(str[3*j:3*j+2]))

M = np.array(M)
h,w = M.shape

# Function to try every 4-products
def max_prod(L) :
    maxi = 0
    for i in range(len(L)-4) :
        t = prod_list(L[i:i+4])
        if t > maxi :
            maxi = t
    return maxi

solution = 0
for i in range(h) :
    # Try on every row
    solution = max(max_prod(M[i]),solution)
    # Try on every column
    solution = max(max_prod(M[:,i]),solution)
    
for k in range(4,h):
    # Try on diagonals (left-bottom-corner to rigth-up-corner)
    solution = max(max_prod([M[h-1-i,h-k+i] for i in range(k)]),solution)
    solution = max(max_prod([M[i,k-i] for i in range(k+1)]),solution)
    
print(solution)

70600674

#### Problem 12 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

+ 1: 1
+ 3: 1,3
+ 6: 1,2,3,6
+ 10: 1,2,5,10
+ 15: 1,3,5,15
+ 21: 1,3,7,21
+ 28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [14]:
Prem = crible(100000)

In [15]:
# This function takes a number and the list of primes that divides this number
# And return the total number of divisors of this number
def f(L,m) :
    t = len(L)
    LO = [0]*t
    for i in range(t) :
        n = m
        while n%L[i] == 0 :
            LO[i]+=1
            n/=L[i]
    P = 1
    for i in range(t) :
        P *= LO[i]+1
    return(P)
        
i,t,n = 1,1,1
while t <= 500 :
    i += 1
    n += i # for every triangular number
    j = 0
    L = []
    # Find out the number of prime numbers that are smaller than sqrt(n)
    while Prem[j] < np.sqrt(n) :
        j += 1
    # Find out the primes that divides n
    for k in range(j+1) :
        if n % Prem[k] == 0 :
            L.append(Prem[k])
    t = f(L,n)
print(n)

76576500

#### Problem 13 
Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

In [16]:
text_file = open("src/13.txt", "r")
lines = text_file.readlines()
text_file.close()

In [17]:
S=0
for i in range(100):
    S+= int(lines[i])
S

5537376230390876637302048746832985971773659831892672

#### Problem 14 
The following iterative sequence is defined for the set of positive integers:

n → n/2 (n is even)
n → 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:

13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

In [18]:
def collatz(n) :
    if n % 2 == 0 :
        return n/2
    else :
        return 3*n+1

maxi = 0
nb = 1
cpt = 1

for i in range(1,1000001) :
    u = i
    cpt = 1
    while u != 1 :
        cpt += 1
        u = collatz(u)
    if cpt > maxi :
        maxi = cpt
        nb = i
        #print(nb,maxi)

print(nb)

837799

#### Problem 15 
Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20×20 grid?

In [19]:
# This is a well-known number : binomial coefficient
# Build a path is like picking up 20 down among 40 choices right or down !
int(fact(40)/(fact(20)**2))

137846528820

### Problem 16 
215 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 2^1000?

In [20]:
# No big deal in python, hopefully
sum_list(int_to_list(2**1000))

1366

#### Problem 17 
If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?


NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

Let's generate the words.

In [21]:
list09 = ['zero','one','two','three','four','five','six','seven','eight','nine']
list1019 = ['ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen']
list2_9_ = ['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety']

In [22]:
def number_to_words(n):
    if n==0:
        return 'zero'
    if n==1:
        return 'one'
    if n==2:
        return 'two'
    else :
        size = math.ceil(np.log10(n+1))
        if size == 1:
            return list09[n]
        elif size == 2 and n<20:
            return list1019[n-10]
        elif size == 2 and n>=20:
            if n%10 == 0:
                return list2_9_[n//10]
            else :
                return list2_9_[n//10]+number_to_words(n%10)
        elif size == 3:
            if n%100 == 0:
                return number_to_words(n//100)+'hundred'
            else :
                return number_to_words(n//100)+'hundredand'+number_to_words(n%100)
        elif n==1000:
            return 'onethousand'
    pass

In [23]:
S=0
for i in range(1,1001):
    S+=len(number_to_words(i))
S

21124

#### Problem 18 
By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

3
7 4
2 4 6
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

+ 75
+ 95 64
+ 17 47 82
+ 18 35 87 10
+ 20 04 82 47 65
+ 19 01 23 75 03 34
+ 88 02 77 73 07 63 67
+ 99 65 04 28 06 16 70 92
+ 41 41 26 56 83 40 80 70 33
+ 41 48 72 33 47 32 37 16 94 29
+ 53 71 44 65 25 43 91 52 97 51 14
+ 70 11 33 28 77 73 17 78 39 68 17 57
+ 91 71 52 38 17 14 91 43 58 50 27 29 48
+ 63 66 04 68 89 53 67 30 73 16 69 87 40 31
+ 04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)

In [24]:
text_file = open("src/18.txt", "r")
lines = text_file.readlines()
lines[-1] += '\n' #uniformizing ...
text_file.close()

In [25]:
size = len(lines)
# We put the triangle into a list of lists
triangle = []

for i in range(size):
    str = lines[i][:-1]
    triangle.append([])
    for j in range(int(len(str)/3)+1):
        triangle[i].append(int(str[3*j:3*j+2]))

In [26]:
Scores = triangle[:]
for i in range(size-1,0,-1):
    for j in range(len(Scores[i-1])):
        Scores[i-1][j] += max(Scores[i][j],Scores[i][j+1])

print("The max path score is :",Scores[0][0])

The max path score is : 1074

#### Problem 19 
You are given the following information, but you may prefer to do some research for yourself.

1 Jan 1900 was a Monday.
Thirty days has September,
April, June and November.
All the rest have thirty-one,
Saving February alone,
Which has twenty-eight, rain or shine.
And on leap years, twenty-nine.
A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.
How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?

In [27]:
def is_leap_year(n) :
    return(n % 100 != 0 and n % 4 == 0) or (n%400 == 0)

# Here is a list of the number of days in every months after 
# the 1st of January in 1901
L= [31,29,31,30,31,30,31,31,30,31,30,31]*100
del(L[-1])
for i in range(1901,2001) :
    if is_leap_year(i) :
        L[(i-1901)*12+1] = 28

# L[i] will be the number of days elapsed since the last 
S = 0
for i in range(len(L)) :
    S += L[i]
    L[i] = S

# Let's count how many months begin with a Sunday
cpt = 0
for i in range(len(L)) :
    if L[i] % 7 == 6 :
        cpt += 1

print(cpt)

175

#### Problem 20 
n! means n × (n − 1) × ... × 3 × 2 × 1

For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

Find the sum of the digits in the number 100!

In [28]:
# Once again, 100! is not that much for Python !
n = fact(100)
L = int_to_list(n)
S = sum_list(L)
S

648